/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
export module ui {
    export class gameMainUI extends Scene {
		public worldMap:Laya.Sprite;
		public map:Laya.Sprite;
		public gameBox:Laya.Sprite;
		public scoreText:laya.display.Text;
		public snakeNumText:laya.display.Text;
		public beanNumText:laya.display.Text;
		public rockerBox:Laya.Sprite;
		public rockerMove:Laya.Sprite;
		public speedBtn:Laya.Button;
		public UI:Laya.Sprite;
		public gameOver:Laya.Sprite;
		public again:Laya.Button;
		public beginUI:Laya.Sprite;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("gameMain");
        }
    }
}